Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "nie-vm"
  config.vm.synced_folder "../..", "/home/vagrant/nie"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end

  config.vm.provision "shell", path: "provision.sh", privileged: true
end
